export default {
  name: 'article',
  title: 'Article',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'summary',
      title: 'Summary',
      type: 'text',
      description: 'Short snippet used for the article intro and social media links',
    },
    {
      name: 'author',
      title: 'Author',
      type: 'reference',
      to: [{ type: 'author' }],
    },
    {
      name: 'mainImage',
      title: 'Main image',
      type: 'image',
      options: {
        hotspot: true,
      },
    },
    {
      name: 'category',
      title: 'Section',
      type: 'string',
      options: {
        list: [
          { title: 'Ghana', value: 'ghana' },
          { title: 'Politics', value: 'politics' },
          { title: 'Business', value: 'business' },
          { title: 'Sports', value: 'sports' },
          { title: 'Football', value: 'football' },
          { title: 'Transfers', value: 'transfers' },
          { title: 'STEM', value: 'stem' },
          { title: 'Entertainment', value: 'entertainment' },
          { title: 'World', value: 'world' },
          { title: 'Opinion', value: 'opinion' },
        ],
        layout: 'dropdown',
      },
    },
    {
      name: 'subsection',
      title: 'Subsection',
      type: 'string',
      hidden: ({ document }) => !document?.category, 
      options: {
        list: [
          { title: 'Sports: Match Reports', value: 'match-reports' },
          { title: 'Sports: Transfers & Rumors', value: 'transfers' },
          { title: 'Sports: Editorials', value: 'sports-editorials' },
          { title: 'Politics: Local News', value: 'local-news' },
          { title: 'Politics: International', value: 'international' },
          { title: 'Politics: Editorials', value: 'politics-editorials' },
          { title: 'Entertainment: Celebrity', value: 'celebrity' },
          { title: 'Entertainment: Music & Film', value: 'music-film' },
        ],
        layout: 'dropdown',
      },
    },
    {
      name: 'publishedAt',
      title: 'Published at',
      type: 'datetime',
    },
    {
      name: 'body',
      title: 'Body',
      type: 'array',
      of: [{ type: 'block' }, { type: 'image' }],
    },
    {
      name: 'content',
      title: 'Legacy Content (Migrated)',
      type: 'array',
      of: [{ type: 'block' }, { type: 'image' }],
      hidden: () => true,
    },
    {
      name: 'editorialCategory',
      title: 'Legacy Editorial Category',
      type: 'reference',
      to: [{ type: 'author' }], 
      weak: true,
      hidden: () => true,
    },
    {
      name: 'oldHygraphCategory',
      title: 'Old Hygraph Category',
      type: 'string',
      hidden: () => true,
    },
  ],
}